databases:
  - name: ruby_postgres
    databaseName: ruby_postgres
    user: ruby_postgres
    plan: free

services:
  - type: web
    name: ruby
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false